name: Development

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Clone:
    runs-on: homeyhuts-dev
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4
        with:
          path: 'dev'

  Build:
    runs-on: homeyhuts-dev
    needs: Clone
    defaults:
        run:
          working-directory: dev
    steps:
      - name: Installing Dependencies
        run: pnpm install

  Deploy:
    runs-on: homeyhuts-dev
    needs: Build
    steps:
      - name: Restarting Systemd Service
        run: sudo service chatbot-react-dev restart
